server:
  port: 8865

spring:
  application:
    name: poc-spring-cloud-zuul-correlation-id

eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true 
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/